### ISSUE TITLE
static errorpage shows betternavigator

### ISSUE THREAD

**Issue by mikeyc7m** [jonom/silverstripe-betternavigator#16]
the static error pages are including the betternavigator code. need to exclude it.

**Comment by jonom** [comment]
Hi @mikeyc7m I'm pretty sure you'll find this only happens if the site is in dev mode. If I'm wrong about this or you think it needs to be fixed anyway feel free to re-open this and submit a patch. Cheers

**Comment by mikeyc7m** [comment]
i think perhaps my dev static page may have snuck onto the live site, i've republished and it's gone. so yup, no issue.
