### ISSUE TITLE
Developer error messages from Sourcemap

### ISSUE THREAD

**Issue by MattyBalaam** [jonom/silverstripe-betternavigator#29]
betternavigator.css.map contains references to compass scss files. These cause errors and/or unneccesary clutter in some developer consoles.

![image](https://cloud.githubusercontent.com/assets/1246923/25617845/28f58652-2f3c-11e7-9d4b-3cdafe2454db.png)

![image](https://cloud.githubusercontent.com/assets/1246923/25617867/448dbaf6-2f3c-11e7-8e49-fe4b9c56188a.png)

**Comment by jonom** [comment]
Huh, so it does! Feel free to submit a PR to correct if you like. Could remove Compass dependency, or just change source map setting to false, cut out the reference from the end of the CSS file and delete the source map file.
