### ISSUE TITLE
Position and translucent config feature

### ISSUE THREAD

**Issue by 3Dgoo** [jonom/silverstripe-betternavigator#51]
Hi Jono,

I have created a fork and a branch of this module for myself with some minor features. I thought I would share the changes with you in case you were interested in merging in any of these.

This is the branch:
https://github.com/3Dgoo/silverstripe-betternavigator/tree/feature/navigator-location-config

When I use the better navigator I usually drop it down to the bottom right of the site so it doesn't clash with the site navigation. I also make it semi-transparent when not active. 

I've created this branch that allows us to set the position (left-top, right-top, right-bottom or left-bottom) through the config. If the config value is not set it defaults to right-top.

In the branch, we can also toggle the semi-transparent styling on and off through the config too.

Let me know if you're keen on using any of this. If not, all cool. Feel free to close this issue either way.

Thanks.

**Comment by jonom** [comment]
@3Dgoo being able to choose a corner to pin the tools is something I always intended to add, but never got around to - so yes please!

Translucency is probably less helpful, but certainly won't do any harm, so I'm happy for that to be added as well.

Please feel free to open a PR :)
