### ISSUE TITLE
Make CMS Link work for Data Objects

### ISSUE THREAD

**Issue by purplespider** [jonom/silverstripe-betternavigator#54]
Is there an easy way to make the "Edit in CMS" link work for a page displaying a DataObject? e.g. to take you to editing that DataObject in the existing ModelAdmin/GridField? (Currently, it just takes you to editing the page).

**Comment by jonom** [comment]
I'm not certain, but I think overloading `CMSEditLink()` would do the trick.

**Comment by purplespider** [comment]
Ah, thanks! I had explored this before, but obviously in the wrong way.

So I can see that setting `CMSEditLink()` on the Page does affect the Edit link in BetterNavigator, however, I somehow need to get the `action` and `ID` from the request so it knows which DataObject to edit, but the request is only available in the PageController.

Am I missing something obvious? Or does this mean it would be more complex than initially expected to do this for BetterNavigator?

**Comment by jonom** [comment]
Ah, I didn't consider that. What happens if you put `CMSEditLink()` on your controller instead? I'm guessing it won't pick it up, but could be worth a try.

**Comment by purplespider** [comment]
> What happens if you put `CMSEditLink()` on your controller instead? I'm guessing it won't pick it up, but could be worth a try.

Yeh, I tried many different variants of this, but just couldn't find a way to override it without adding the ability within BetterNavigator itself.
