### ISSUE TITLE
v6 ToDo

### ISSUE THREAD

**Issue by jonom** [jonom/silverstripe-betternavigator#63]
- [ ] Namespace config

**Comment by xini** [comment]
Happy to submit a PR. What class do you want the config to be attached to? `BetterNavigatorExtension` or the owner?

**Comment by jonom** [comment]
Thanks @xini, would be appreciated! Have been struggling to keep up as you may have noticed 😂 I like `JonoM\BetterNavigator` for simplicity but maybe we should put it on the extension, then we can use the [Configurable trait](https://docs.silverstripe.org/en/5/developer_guides/configuration/configuration/#configuration-properties).

**Comment by xini** [comment]
@jonom I don't mind. If we put it on the extension, the two existing config properties (`$better_navigator_edit_permission`) that should be used on the owner of the extension (controller) are mixed with the new config properties. I don't mind, but maybe that might be a bit confusing? So maybe a pseudo namespace `JonoM\BetterNavigator` works better here? Your call.

**Comment by jonom** [comment]
Yeah let's go with `JonoM\BetterNavigator`. Thanks!

**Comment by xini** [comment]
Done, see #64.
