### ISSUE TITLE
Feature request: feature flag

### ISSUE THREAD

**Issue by Jianbinzhu** [jonom/silverstripe-betternavigator#68]
Hey, can we add a feature flag to hide this feature? My use case is this is breaking some of my e2e tests, it would be great if we can add a feature flag (env variable) to hide this feature.

Let me know what you think 🙏

**Comment by xini** [comment]
You can set your own env variable and create a 'showBetterNavigator()' method in your page controller that checks your var, see https://github.com/jonom/silverstripe-betternavigator?tab=readme-ov-file#navigator-display

**Comment by Jianbinzhu** [comment]
> You can set your own env variable and create a 'showBetterNavigator()' method in your page controller that checks your var, see https://github.com/jonom/silverstripe-betternavigator?tab=readme-ov-file#navigator-display

Thanks, that resolved my issue 😅
